### ISSUE TITLE
Can't find /etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY

### ISSUE THREAD

**Issue by somethingweird** [iuscommunity/automation-examples#15]
in https://setup.ius.io 

CENTOS 7

the script is looking for /etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY

should it be /etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-7

**Comment by carlwgeorge** [comment]
Yes, this is related to the IUS CDN changes.

https://github.com/iusrepo/infrastructure/issues/14

This will be fixed soon.

**Comment by carlwgeorge** [comment]
Fixed in 038e5c0fe771ba7af36e20ab81f51fb0adf3a818.

**Comment by carlwgeorge** [comment]
This is now deployed on https://setup.ius.io.
