### ISSUE TITLE
Ansible playbook failed

### ISSUE THREAD

**Issue by tovletoglou** [iuscommunity/automation-examples#4]
Trying to run the Ansible playbook: `ansible-playbook -i "hosts" enable-ius.yml` I get the error: `Failure downloading https://centos7.iuscommunity.org/ius-release.rpm, 'NoneType' object has no attribute 'read'`

Running with `-vvvv`

    TASK [install IUS release package] *********************************************
    task path: /home/vagrant/ansible-playbook-aegir-centos/enable-ius.yml:24
    <haproxy.dev> ESTABLISH SSH CONNECTION FOR USER: None
    <haproxy.dev> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r haproxy.dev '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478002414.39-180297584212514 `" && echo ansible-tmp-1478002414.39-180297584212514="` echo $HOME/.ansible/tmp/ansible-tmp-1478002414.39-180297584212514 `" ) && sleep 0'"'"''
    <haproxy.dev> PUT /tmp/tmpcDwJ_w TO /home/vagrant/.ansible/tmp/ansible-tmp-1478002414.39-180297584212514/yum
    <haproxy.dev> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r '[haproxy.dev]'
    <haproxy.dev> ESTABLISH SSH CONNECTION FOR USER: None
    <haproxy.dev> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r haproxy.dev '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1478002414.39-180297584212514/ /home/vagrant/.ansible/tmp/ansible-tmp-1478002414.39-180297584212514/yum && sleep 0'"'"''
    <haproxy.dev> ESTABLISH SSH CONNECTION FOR USER: None
    <haproxy.dev> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r -tt haproxy.dev '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-qhedrztmtfnuecabiruxawxazzdnjrzl; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1478002414.39-180297584212514/yum; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1478002414.39-180297584212514/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
    fatal: [haproxy.dev]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["https://centos7.iuscommunity.org/ius-release.rpm"], "state": "present", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "msg": "Failure downloading https://centos7.iuscommunity.org/ius-release.rpm, 'NoneType' object has no attribute 'read'"}

Something else I notice and maybe help; When you run a task to install the epel repo using the `state: latest` it fails instead when you run as `state: present` 

This one will fail:

    - name: Install epel repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: latest

But this one will work:

    - name: Install epel repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

Unfortunately doing the same on for the IUS repo it always fails:

    - name: Install IUS repo
      yum:
        name: https://centos7.iuscommunity.org/ius-release.rpm
        state: present

**Comment by b-harper** [comment]
Hey @tovletoglou,

Thanks for taking the time to submit this issue.  Personally, I do not have much experience with Ansible.  Looking at the error message, it would seem that the server in question can not access the IUS release URL.  Can you confirm the following from the server in question:

```
$ curl -I https://centos7.iuscommunity.org/ius-release.rpm
HTTP/1.1 301 Moved Permanently
Date: Tue, 01 Nov 2016 13:57:09 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips
Location: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm
Content-Type: text/html; charset=iso-8859-1
```

```
$ curl -I https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 01 Nov 2016 14:41:27 GMT
Content-Type: application/x-redhat-package-manager
Content-Length: 8264
Last-Modified: Tue, 01 Nov 2016 04:16:36 GMT
Connection: keep-alive
ETag: "58181724-2048"
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
```

If you are able to access these URLs, you might want to try using the full URL, 'https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm'.  The way that EPEL and IUS handles the latest release URLs are different.  IUS uses a 301 redirect while EPEL returns a 200.  I am not sure if that will make a difference, but it might be worth a try.

Also, what version of Ansible are you using?

**Comment by tovletoglou** [comment]
Hi @b-harper thanks for the quick reply.
I'm running `ansible 2.1.2.0`
Both commands return the exact same output with yours. 

But trying the Ansible role:

    - name: Install IUS
      yum:
        name: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm
        state: present

Returns the error:

    TASK [ansible-role-git : Install ius] ******************************************
    task path: /home/vagrant/ansible-playbook-aegir-centos/roles/ansible-role-git/tasks/git-install-from-repository.yml:8
    <haproxy.dev> ESTABLISH SSH CONNECTION FOR USER: None
    <haproxy.dev> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r haproxy.dev '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478020201.94-274781954102298 `" && echo ansible-tmp-1478020201.94-274781954102298="` echo $HOME/.ansible/tmp/ansible-tmp-1478020201.94-274781954102298 `" ) && sleep 0'"'"''
    <haproxy.dev> PUT /tmp/tmpU5OTlk TO /home/vagrant/.ansible/tmp/ansible-tmp-1478020201.94-274781954102298/yum
    <haproxy.dev> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r '[haproxy.dev]'
    <haproxy.dev> ESTABLISH SSH CONNECTION FOR USER: None
    <haproxy.dev> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r haproxy.dev '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1478020201.94-274781954102298/ /home/vagrant/.ansible/tmp/ansible-tmp-1478020201.94-274781954102298/yum && sleep 0'"'"''
    <haproxy.dev> ESTABLISH SSH CONNECTION FOR USER: None
    <haproxy.dev> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r -tt haproxy.dev '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ggucypfbxrfsxjrpulnqcprkzrtnsgvj; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1478020201.94-274781954102298/yum; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1478020201.94-274781954102298/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
    fatal: [haproxy.dev]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm"], "state": "present", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "msg": "Failure downloading https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm, 'NoneType' object has no attribute 'read'"}

Probably something is going wrong with Ansible and the 301 redirect.

**Comment by tovletoglou** [comment]
Now I'm trying the Ansible task `yum_repository` https://docs.ansible.com/ansible/yum_repository_module.html that seems more appropriate to setup a repository.

Here is an example role to install IUS using `yum_repository` on Centos 7.

    - name: Add IUS repository to /etc/yum.repos.d/
      yum_repository:
        name: ius
        file: ius
        description: IUS Community Packages for Enterprise Linux 7 - $basearch
        mirrorlist: https://mirrors.iuscommunity.org/mirrorlist?repo=ius-centos7&arch=$basearch&protocol=http
        gpgkey: http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY
        enabled: yes
        gpgcheck: yes

**Comment by carlwgeorge** [comment]
In your last example, the url `https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm` is not a 301 redirect, that is the exact path to the rpm.  It appears that while yum supports installing from a url, the ansible yum module does not.  The final part of your error message, `'NoneType' object has no attribute 'read'`, usually indicates that something unexpected happened in the Python code.

The yum_repository module seems useful, but we would still prefer an approach that gets our official ius-release rpm installed on the system, so I'm not sure what the best solution would be for this example playbook.  Perhaps a two step download and install?  That would require the ansible yum module to support installing a local rpm file (I'm not sure if it does or not).

**Comment by b-harper** [comment]
@scottsb,

As someone that contributed this Ansible example, do you have any idea whats happening or changes that might need to be made?

**Comment by chrishultin** [comment]
tovletoglou:  I've got a slightly modified version of the enable-ius.yml file linked below.  Can you try running this and letting us know what you get for the output?

https://gist.github.com/chrishultin/d986c13772da1f5d7f6d2d6152b45c8c

**Comment by tovletoglou** [comment]
It will drive me crazy... Running the following task from a Vagrant, Centos 7.2, Ansible 2.1.2.0

    # Must be state: present due to deficiency in ansible. See:
    # https://github.com/ansible/ansible-modules-core/issues/948 
    - name: install IUS release package
      yum:
        name: "https://{{ ius_distribution_abbrev }}{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm"
        state: present
      when: ansible_os_family == 'RedHat'
      register: install_via_url
      ignore_errors: yes

to a DigitalOcean, Centos 7.2 VM everything goes ok!
to a Vagrant, Centos 7.2 VM reports:

    fatal: [vagrant.dev]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading https://centos7.iuscommunity.org/ius-release.rpm, 'NoneType' object has no attribute 'read'"}

Running the @chrishultin's playbook failed on VMs that can install from URL. But this is not a real issue.

      fatal: [digitalocean.vm]: FAILED! => {
      "failed": true,
      "msg": "The conditional check 'install_via_url.failed' failed. The error was: error while evaluating conditional (install_via_url.failed): 'dict object' has no attribute 'failed'

      The error appears to have been in '/home/vagrant/ansible-playbook-aegir-centos/ius.yml': line 32, column 7, but may
      be elsewhere in the file depending on the exact syntax problem.

      The offending line appears to be:

          - name: download IUS release package
          ^ here"
      }

**Comment by tovletoglou** [comment]
@carlwgeorge I don't know how `https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm` works to setup a repo, but it will make something different from creating (on a Centos system) these files?

    /etc/yum.repos.d/ius.repo
    /etc/yum.repos.d/ius-archive.repo
    /etc/yum.repos.d/ius-dev.repo
    /etc/yum.repos.d/ius-testing.repo

**Comment by b-harper** [comment]
So I got asking around to some folks that know and use Ansible.  This [pull request][0] got created for better error reporting.  Someone else mentioned the difference between 'state=present' and 'state=latest', but it seems you have tried both without any luck.  A third person voiced frustration about the overall state of the yum module.  

In regards to using the ius-release RPM, it is not so much about initially creating the repositories, but having a smooth transition if they need to get updated.  Generally we recommend using the ius-release RPM, but there are some cases where it does not make sense, like if you run your own private mirror.  If end up not using the ius-release RPM, I would recommend watching our [announce repository][1] as that is where we would announce any changes.

[0]: https://github.com/ansible/ansible-modules-core/issues/5474
[1]: https://github.com/iuscommunity/announce

**Comment by b-harper** [comment]
@tovletoglou, were you able to make any progress?

That pull request got merged, but it is not clear when it will make it into a proper release.

**Comment by tovletoglou** [comment]
We decide to drop the `yum` installation and keep the `yum_repository` task for the moment. The only problem is that we miss the official changes on the ius-release rpm.

**Comment by b-harper** [comment]
@tovletoglou,

Thanks for the update.  We try to change the ius-release RPM as little as possible.  That being said, I would recommend watching the [announce repository][0] and/or the [ius-release][1] repositories.  

[0]: https://github.com/iuscommunity/announce
[1]: https://github.com/iuscommunity-pkg/ius-release
