### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by yggdr** [iuscommunity/automation-examples#8]
Please add a license or a clarifying statement under which conditions the scripts can be used, thank you!

**Comment by b-harper** [comment]
@yggdr,

Thanks for taking the time to contact us.  

@carlwgeorge and @scottsb, do yall have any license preference or thoughts on usage?

**Comment by carlwgeorge** [comment]
Since these are just simple examples, I would prefer something simple and permissive, such as the [Unlicense](https://choosealicense.com/licenses/unlicense/) or [MIT](https://choosealicense.com/licenses/mit/).
